version: "3.8"

services:
    client:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        ports:
            - "5173:5173"
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - VITE_SERVER_URL=ws://localhost:2567
