version: "3.8"

services:
    client:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        ports:
            - "5173:5173"
        volumes:
            - .:/app
        environment:
            - VITE_SERVER_URL=ws://localhost:2567
        command: sh -c "npm ci && npm run dev -- --host 0.0.0.0"
